export const PRIMARY_BACKGROUND_COLOR = '#1A1A1A';
export const SECONDARY_BACKGROUND_COLOR = '#C4C4C4';
export const DISABLE_BACKGROUND_COLOR = '#999999';

export const PRIMARY_TEXT_COLOR = '#EDF6FF';
export const SECONDARY_TEXT_COLOR = '#DADADA';
export const PLACEHOLDER_TEXT_COLOR = '#979797';
export const HINT_TEXT_COLOR = '#535AFF';

export const PRIMARY_BORDER_COLOR = '#979797';
export const SECONDARY_BORDER_COLOR = '#EDF6FF';

export const PRIMARY_ICON_COLOR = '#EDF6FF';

export const DRAWER_BACKGROUND_COLOR = '#535AFF';

export const WHITE_COLOR = '#FFFFFF';

export const PRIMARY_GRADIENT_COLOR = {
  COLOR_1: '#000000',
  COLOR_2: '#000000',
  COLOR_3: '#000000',
};
export const SECONDARY_GRADIENT_COLOR = {
  COLOR_1: '#1976D2',
  COLOR_2: '#3867EA',
  COLOR_3: '#535AFF',
};
